Module1 task3
htmlacademy-react/814025-six-cities-5 pull request #3
Opened 2020-10-03 11:37 UTC by NatalyLu

2020-10-03 18:16 UTC, bini1988 requested changes

2020-10-03 18:16 UTC, bini1988 commented on src/components/index/article/Article.jsx
> +const Article = (props) => {
Здесь и далее необходимо привести именование файлов папок и компонентов согласно критерию [Б36](https://up.htmlacademy.ru/react/5/criteries#b36), плюс я бы расположи все компоненты на одном уровне в папке `components`

2020-10-03 18:16 UTC, bini1988 commented on src/components/app/App.jsx
> +import Index from "../index/index";
Для компонента `Index` необходимо подобрать другое название, например, `IndexPage`, критерий [Б37](https://up.htmlacademy.ru/react/5/criteries#b37) не позволяет использовать название `index.js` для компонентов

2020-10-03 18:16 UTC, bini1988 commented on src/components/index/index.jsx
> +      <header className="header">
Я бы предложим элемент `<header className="header">` так же перенести внутрь компонента `Header`

2020-10-03 18:16 UTC, bini1988 commented on src/components/index/article/Article.jsx
> +    </div>
Наверно здесь должна быть верстка блока`<article class="cities__place-card place-card">...</article>`?

2020-10-03 18:20 UTC, bini1988 commented
Есть замечания по критериям и стилю именования файлов проекта, лучше поправить их на начальном этапе. Понравилась идея разбиения на подкомпоненты, однако исходная верстка отличается от макета, как минимум пустой список предложения, необходимо добавить соответствующую верстку в компонент `Article` (можно создать статический компонент `Article` с одним вариантом верстки, позже мы его будем использовать для отображения списка предложений).

2020-10-03 20:32 UTC, NatalyLu commented on src/components/index/article/Article.jsx
> +    </div>
верно, но в ней используются теги со стилями, прописанными внутри них, из-за чего в консоли много разных ошибок. Сначала я думала, что проблема в теге use, так как именно на него указывала студия. Но потом выяснила реальную ошибку :) 
я пока вставлю фрагмент с одной карточкой, но закомментирую спаны со стилями внутри.
![image](https://user-images.githubusercontent.com/45073400/95000550-7d616680-05ca-11eb-81d7-d7b57ec3e9b6.png)

2020-10-04 09:26 UTC, bini1988 commented on src/components/index/article/Article.jsx
> +    </div>
jsx имеет различия с html, [здесь можно почитать подробнее](https://ru.reactjs.org/docs/dom-elements.html), плюс если элемент не имеет вложенных пишут сокращенно, например, `<use xlinkHhref="#icon-arrow-select"/>`

2020-10-04 09:27 UTC, merged