Module4 task1
htmlacademy-react/814025-six-cities-5 pull request #6
Opened 2020-11-08 23:26 UTC by NatalyLu

2020-11-09 10:14 UTC, bini1988 requested changes
Есть небольшие замечания, плюс необходимо отобразить все маркеры предложений на карте.

2020-11-09 10:14 UTC, bini1988 commented on src/components/card/card.jsx
> +  const {imgWidth = `80%`} = props.infoForCard.imgWidth;
Этот параметр должен рассчитываться на основе значения `props.offer.rating`

2020-11-09 10:14 UTC, bini1988 commented on src/components/card/card.jsx
> +        <Link to={infoForCard.offerLink}>
Я думаю что в данном случае ссылку на предложение можно формировать внутри компонента `Card`

2020-11-09 10:14 UTC, bini1988 commented on src/components/favorites-locations/favorites-locations.jsx
> +  const infoForCard = {
Аналогично, предлагаю избавиться от группировки и передавать поля объекта `infoForCard` как набор пропсов компонента `Card`

2020-11-09 10:14 UTC, bini1988 commented on src/components/favorites-locations/favorites-locations.jsx
> +                <span>{capitalizeFirstLetter(favCity)}</span>
Имена городов будут приходить с сервера с большой буквы, думаю здесь нет смысла в дополнительном форматировании

2020-11-09 10:14 UTC, bini1988 commented on src/components/header/header.jsx
> +  const headerInfo = props.headerInfo;
Аналогично, я бы предложил избавиться от группировки параметров в объект и возможно `logoLink` прописать внутри компонента `Header`

2020-11-09 10:14 UTC, bini1988 commented on src/components/main-map/main-map.jsx
> +    const offerCords = [this.offer.location.latitude, this.offer.location.longitude];
Думаю здесь необходим цикл по `this.offersSameCity` где для каждого `offer` из списка вызываем:
```js
    const offerCords = [offer.location.latitude, offer.location.longitude];
    leaflet.marker(offerCords, {icon}).addTo(map);
```

2020-11-10 16:18 UTC, bini1988 approved these changes
Есть небольшие замечания и предложения, но в целом все хорошо, предлагаю двигаться дальше к `redux` и общению с сервером.

2020-11-10 16:18 UTC, bini1988 commented on src/components/articles/articles.jsx
> +    this.cardImageClasses = `cities__image-wrapper`;
Это уже интересно, но все еще не вижу причин для создания полей класса, думаю вполне обойтись прямым описанием значений данных пропсов в JSX разметке

2020-11-10 16:18 UTC, bini1988 commented on src/components/header/header.jsx
> +  // headerInfo: headerInfoPropTypes
Перед защитой надо убедиться чтобы не осталось закомментированных участков кода

2020-11-10 16:18 UTC, bini1988 commented on src/components/index-page/index-page.jsx
> +  const mapClasses = `cities__map`;
Аналогично, думаю здесь нет необходимости объявлять дополнительные переменные, это лишь усложняет чтение кода, заставляя бегать вниз-вверх по коду

2020-11-10 16:18 UTC, bini1988 commented on src/components/main-map/main-map.jsx
> +      </Fragment>
Для добавление маркеров на карту мы используем API библиотеки leaflet, она никак не привязана к React, нет смысла использовать здесь `Fragment`.

2020-11-10 16:18 UTC, bini1988 commented on src/func.js
> +  offers.map((item) => (allParameters.push(item.city.name)));
Можно сократить до `const allParameters = offers.map((item) => item.city.name);`

2020-11-10 16:18 UTC, bini1988 commented on src/prop-types.js
> +export const userNamePropTypes = PropTypes.string;
Спорно на сколько это оправдано, мне кажется это только усложняет код, приходится навигироваться по файлам чтобы понять что за тип спрятан за `userNamePropTypes`

2020-11-10 16:18 UTC, merged

2020-11-14 13:14 UTC, NatalyLu commented on src/components/main-map/main-map.jsx
> +      </Fragment>
А куда в таком случае можно вставить ключ?

2020-11-14 13:23 UTC, NatalyLu commented on src/prop-types.js
> +export const userNamePropTypes = PropTypes.string;
т.е. можно некоторые типы переменных описывать в отдельном файле(prop-types), а некоторые непосредственно там, где они используются?
В нашем случае userNamePropTypes используется в header, выходит, я могу определить тип следующим образом:
Header.propTypes = {
  userName: PropTypes.string;,
};
не будет ли это считаться плохим тоном?

2020-11-14 14:02 UTC, bini1988 commented on src/components/main-map/main-map.jsx
> +      </Fragment>
Какой именно ключ и для чего его куда то вставлять? Если речь идет про пропс `key` то он здесь не нужен, leaflet не рендерит React компоненты.

2020-11-14 14:06 UTC, bini1988 commented on src/prop-types.js
> +export const userNamePropTypes = PropTypes.string;
> т.е. можно некоторые типы переменных описывать в отдельном файле(prop-types), а некоторые непосредственно там, где они используются?

Да, мы выносим сложные типы, вроде объектов предложения и отзыва, чтобы не дублировать их в разных частях кода. Выносить простые типы вроде `string` или `number` большого смысла нет, что касается имени пользователя, то на мой взгляд это тоже является частью сложно типа, например:
```js
export const userProfile = PropTypes.shape({
  name: PropTypes.string.isRequired,
  avatar: PropTypes.string.isRequired,
}).isRequired;
```

2020-11-14 14:28 UTC, NatalyLu commented on src/components/main-map/main-map.jsx
> +      </Fragment>
хорошо, тогда я заменю map на forEach, будет выглядеть судующим образом
// Добавим на карту маркеры
    this.offers.forEach((item) => {
      this.renderCore(item, {icon}, map);
    });

2020-11-14 14:32 UTC, NatalyLu commented on src/prop-types.js
> +export const userNamePropTypes = PropTypes.string;
поняла. На данный момент, а компоненте header нужно только стринговое имя, поэтому я пока буду использовать упрощенную запись
Header.propTypes = {
userName: PropTypes.string;,
};