Module5 task1
htmlacademy-react/814025-six-cities-5 pull request #7
Opened 2020-11-16 20:04 UTC by NatalyLu

2020-11-17 09:15 UTC, bini1988 requested changes

2020-11-17 09:15 UTC, bini1988 commented on src/components/main-map/main-map.jsx
> +  const offersSameCity = props.offersSameCity;
Здесь часто используют деструктуризацию:
```js
const { mapClasses, offersSameCity } = props;
```

2020-11-17 09:15 UTC, bini1988 commented on src/components/map/map.jsx
> +  renderCore(item, icon, map) {
Небольшой диссонанс по названию, `core` это ядро, часто употребляется в качестве обозначения "ядра" основной логики библиотеки/приложения, думаю здесь логичней уточнить `renderCoordinates`

2020-11-17 09:15 UTC, bini1988 commented on src/components/map/map.jsx
> +    this.offersSameCity = this.props.offersSameCity;
Лучше избегать копирования значений из `this.props` в поля класса, это не очевидно и может привести к ошибкам, плюс в большинстве случаев этом нет необходимости

2020-11-17 09:15 UTC, bini1988 commented on src/reducer.js
> +      return state.offers;
Здесь происходит перетирание объекта `state` списком предложений, необходимо использовать `extend` сохраняя значение в поле `offers` по аналогии с `offersSameCity`

2020-11-17 10:04 UTC, bini1988 requested changes

2020-11-17 10:04 UTC, bini1988 commented on src/components/locations/locations.jsx
> +  const uniqueCities = getArrayOfCities(getAllOffersList());
По [ТЗ](https://up.htmlacademy.ru/react/5/project/six-cities) список городов заранее определен, можно сохранить его в массив-константе и либо положить в `initialState` либо экспортировать напрямую.

2020-11-20 11:13 UTC, bini1988 requested changes
Оставил комментарии к карте и редюсеру

2020-11-20 11:13 UTC, bini1988 commented on src/components/map/map.jsx
> +  componentDidUpdate() {
`componentDidUpdate` принимает аргументы с предыдущим значением пропсов и состояния, думаю есть смысл оптимизировать обновление карты:
```js
componentDidUpdate(prevProps) {
  if (this.props.offersSameCity !== prevProps.offersSameCity) {
  // Здесь обновляем позицию и маркеры на карте
  }
}
```

2020-11-20 11:13 UTC, bini1988 commented on src/components/map/map.jsx
> +    leaflet.layerGroup(markers).addTo(this.map);
Слой с маркерами создается один раз в `componentDidMount` и далее используется на протяжении всей жизни компонента:

```js
componentDidMount() {
    this._layerGroup = leaflet.layerGroup().addTo(this.map);
}

addMarkers() {
    this._layerGroup.clearLayers();
    // Добавляем маркеры в цикле
    leaflet.marker(coordinate, { icon }).addTo(this._layerGroup);
}
```

2020-11-20 11:13 UTC, bini1988 commented on src/components/property-page/property-page.jsx
> +    nearPlaces.push(this.offers[1], this.offers[2], this.offers[3], this.offer);
Здесь достаточно воспользоваться мок массивом `offers`, если надо обрезать массив можно использовать `offers.slice(0, 4)`

2020-11-20 11:13 UTC, bini1988 commented on src/reducer.js
> +      const result = newFav[0].isFavorite ? (newFav[0].isFavorite = false) : (newFav[0].isFavorite = true);
```js 
{
  offersFavorites: state.offers
     .filter(it => it.id === action.favoriteId ? {...it, isFavorite: !it.isFavorite } : it)
     .filter(it => it.isFavorite);
}
```

2020-11-20 21:21 UTC, NatalyLu commented on src/components/property-page/property-page.jsx
> +    nearPlaces.push(this.offers[1], this.offers[2], this.offers[3], this.offer);
точно! отличная идея

2020-11-21 17:54 UTC, bini1988 commented on src/reducer.js
> +      const result = newFav[0].isFavorite ? (newFav[0].isFavorite = false) : (newFav[0].isFavorite = true);
Ошибся, вот исправленная версия:
```js 
{
  offersFavorites: state.offers
     .map(it => it.id === action.favoriteId ? {...it, isFavorite: !it.isFavorite } : it)
     .filter(it => it.isFavorite);
}
```

2020-11-22 10:41 UTC, bini1988 approved these changes

2020-11-22 10:41 UTC, bini1988 commented on src/components/map/map.jsx
> +      this.map.removeLayer(this.markGroup);
Вариант с `removeLayer` хорошая идея, единственное предложение перенести:
```js
if (this.markGroup) { 
 this.map.removeLayer(this.markGroup);
}
```
внутрь функции `addMarkers` дабы исключить случая, когда мы забыли вызвать ` this.map.removeLayer(this.markGroup);` перед вызовом `this.addMarkers(offersSameCity);` и удалить из памяти больше не используемые слой карты

2020-11-22 10:41 UTC, merged