Module5 task2
htmlacademy-react/814025-six-cities-5 pull request #9
Opened 2020-11-24 22:25 UTC by NatalyLu

2020-11-25 13:22 UTC, bini1988 requested changes
В целом все хорошо, предлагаю доработать выпадающий список типов сортировки.

2020-11-25 13:22 UTC, bini1988 commented on src/components/card/card.jsx
> +    changeMapMarkerUrl(`img/pin-active.svg`, offer.id);
Думаю достаточно хранить идентификатор выбранного предложения, тип отображаемого маркера для выбранного предложения лучше хранить внутри компонента `Map`.

2020-11-25 13:22 UTC, bini1988 commented on src/components/favorites-locations/favorites-locations.jsx
>    const uniqueFavoriteCities = getArrayOfCities(offersFavoritesSorted);
В ТЗ сказано что:
> На главной странице отображается список городов, для которых возможно запросить предложения по аренде: Paris, Cologne, Brussels, Amsterdam, Hamburg, Dusseldorf. Сервер всегда возвращает информацию только для этих шести городов.

То-есть список городов можно вынести в константу - массив строк.

2020-11-25 13:22 UTC, bini1988 commented on src/components/favorites-locations/favorites-locations.jsx
> +  const offersFavoritesSorted = props.offersFavorites.sort(sortArrayByFieldHighToLow(`city.name`));
Если здесь действительно нужно сортировка, то думаю лучше её вынести в селектор `getFavoritesOffersList`

2020-11-25 13:22 UTC, bini1988 commented on src/components/sorting-options/sorting-options.jsx
> +const SortingOptions = (props) => {
Этот компонент должен работать как выпадающий селект, необходимо добавить к нему внутреннее состояние `isOpen` которое будет менять класс `places__options--opened` по клику на `places__sorting-type`. Плюс, выбранный тип сортировки должен иметь класс `places__option places__option--active`.

2020-11-25 16:35 UTC, NatalyLu commented on src/components/favorites-locations/favorites-locations.jsx
>    const uniqueFavoriteCities = getArrayOfCities(offersFavoritesSorted);
Здесь, мне нужен актуальный массив фаворитных предложений, чтобы отрисовать эти оферы упорядоченно по городам. Но массив будет кстати для списка городов на главной странице (uniqueCities). Лучше положить его в стор или же сделать отдельный селектор для получения городов? Или может быть есть смысл положить массив городов непосредственно в компоненту, в которой происходит отрисовка списка городов?

2020-11-25 18:44 UTC, bini1988 commented on src/components/favorites-locations/favorites-locations.jsx
>    const uniqueFavoriteCities = getArrayOfCities(offersFavoritesSorted);
Я бы добавил селектор, на случай если этот список понадобится где-то еще:
```js
const getOffersCitiesList = state => [`Paris`, `Cologne`, `Brussels`, `Amsterdam`, `Hamburg`, `Dusseldorf`];
```

2020-11-25 20:38 UTC, NatalyLu commented on src/components/favorites-locations/favorites-locations.jsx
>    const uniqueFavoriteCities = getArrayOfCities(offersFavoritesSorted);
а почему селектор, а не просто функцию, которая бы вернула массив?

2020-11-26 12:46 UTC, bini1988 requested changes
После выбора типа сортировки необходимо сворачивать выпадающий список

2020-11-26 12:46 UTC, bini1988 commented on src/action.js
> +  changeMapMarkerUrl: (flagHov, id) => ({
Я бы обобщил в названии цель `выбрать активное предложение` (например `changeActiveOfferId`) нежели уточнял, что именно мы делаем с выбранным предложением (сегодня это url маркеры, завтра полужирное выделение и т.д.).

2020-11-26 12:46 UTC, bini1988 commented on src/components/card/card.jsx
> +  let isHovered = false;
Не думаю что есть смысл в данной переменной, она больше запутывает, поскольку `isHovered=offer.id === mapOfferId`

2020-11-26 12:46 UTC, bini1988 commented on src/components/card/card.jsx
> +          <Link to={offerLink}>{offer.title}</Link>
Не совсем понимаю с какой целью выносится значение пропса в переменную `offerLink`, иногда это полезно, если значение получается путем сложных вычислений, здесь же приходится скролить вверх вниз ради строки в 40 символов.

2020-11-26 12:46 UTC, bini1988 commented on src/components/card/card.jsx
> +    changeMapMarkerUrl(isHovered, offer.id);
Опять же в контексте карточки предложения у нас нет значения ни о карте ни о маркерах на карте, мы предоставляем внешнее API в виде двух событий `onCardFocus` и `onCardBlur`, передавая в них id соответствующего предложения, то как и где эти события и данные будут использовать уже находится за рамками компонента `Card`

2020-11-26 12:46 UTC, bini1988 commented on src/components/favorites-locations/favorites-locations.jsx
>    const uniqueFavoriteCities = getArrayOfCities(offersFavoritesSorted);
Ну если завтра придут и скажут, что список городов надо получать с сервера или формировать на основе списка `offers` то нам достаточно поправить один селектор

2020-11-26 12:46 UTC, bini1988 commented on src/components/locations/locations.jsx
> +  const uniqueCities = getOffersCitiesList();
Вызов `getOffersCitiesList` лучше перенести в `mapStateToProps`

2020-11-26 12:46 UTC, bini1988 commented on src/components/locations/locations.jsx
>              <Link className={`locations__item-link tabs__item ${city === selectedCity && `tabs__item--active`}`} to="#" onClick={(item) => {
Здесь нет необходимости использовать `Link` можно использовать простой тег `a`

2020-11-26 12:46 UTC, bini1988 commented on src/components/locations/locations.jsx
>      changeCity(evt.target.innerText);
Лучше не использовать обращение к `evt.target.innerText`, в крайнем случае хранить значение в `data` атрибутах:
```js
changeCity(evt.target.dataset.value);
...
<a data-value={city}></a> 
```
На практике используют замыкание:
```js
<a onClick={evt => {
evt.preventDefault();
handleChangeCity(city);
}}></a> 
```

2020-11-26 12:46 UTC, bini1988 commented on src/components/map/map.jsx
> +      if ((item.id === this.props.offerId) && (this.props.isCardHover)) {
Не совсем понял для чего нужен `isCardHover` пропс, мы выделяем маркер если `item.id === this.props.offerId`, если `this.props.offerId === null` ни один из маркеров на карте не выделяется.

2020-11-26 12:46 UTC, bini1988 commented on src/components/property-page/property-page.jsx
> +  const offer = offers.find((off) => (off.id === Number(props.id)));
Я бы предложил перенести эту логику в селектор:
```js
const getOfferById = (state, id) => state.offers.find(offer => (offer.id === Number(id)));
```

2020-11-26 12:46 UTC, bini1988 commented on src/components/sorting-options/sorting-options.jsx
> +    tarClasses.add(activeClass);
К сожалению это решение не пройдет критерий [Б12](https://up.htmlacademy.ru/react/5/criteries#b12). Я предлагаю определить массив-константу типов сортировок:
```js
const SORT_TYPES_LIST = [
  label: "Popular", value: "popular",
  label: "Price: low to high", value: "price-low-to-high",
  label: "Price: high to low", value: "price-high-to-low",
  label: "Top rated first", value: "top-rated-first",
];
```
Тогда в рендере компоненте:
```js
    <ul className={`places__options places__options--custom ${props.isOpenList && `places__options--opened`}`} onClick={(evt) => (handleChangeActiveClass(evt, `places__option--active`))}>
      {SORT_TYPES_LIST.map(({ label, value }) => (
        <li className={`places__option ${value === this.props.filterType ? "places__option--active" : ""}`} tabIndex="0" onClick={() => changeFilterType(value)}>{label}</li>
      ))}
    </ul>
```
Здесь текущее значение `filterType` из стора так же необходимо передавать в компонент `SortingOptions `.

2020-11-26 18:16 UTC, NatalyLu commented on src/components/card/card.jsx
> +  let isHovered = false;
а как тогда понять, какой урл маркера ставить, ведь в компоненте map (функция addMarkers) нам нужен какой-нибудь индикатор, чтобы узнать, наведен ли на элемент курсор мыши или снят с него?

2020-11-26 20:24 UTC, NatalyLu commented on src/components/map/map.jsx
> +      if ((item.id === this.props.offerId) && (this.props.isCardHover)) {
да, все верно, но нужно ещё и сбросить маркер обратно в синий, поскольку я не могу узнать текущий урл маркера, то мне необходим флаг (до этого управляла урлами маркеров непосредственно в map.jsx, а теперь заменила эту логику на флаг ховера)

2020-11-27 09:40 UTC, bini1988 approved these changes

2020-11-27 09:40 UTC, bini1988 commented on src/components/card/card.jsx
> +  let isHovered = false;
Самый простой вариант - на `onMouseEnter`  вызываем `changeActiveOfferId(offer.id)`, на `onMouseLeave` вызываем `changeActiveOfferId(null)`, думаю этого будет достаточно  для функционала выделения на карте выбранного предложения.

2020-11-27 09:40 UTC, bini1988 commented on src/components/index-page/index-page.jsx
> +  offersSameCity: getSameCityOffersList(state, state.offers)
Для чего здесь передается второй параметр `state.offers` если мы уже передали `state`?

2020-11-27 09:40 UTC, merged

2020-11-27 17:29 UTC, NatalyLu commented on src/components/index-page/index-page.jsx
> +  offersSameCity: getSameCityOffersList(state, state.offers)
я хотела сделать этот селектор более универсальным, чтобы на вход он получал любой массив и из него отбирал оферы по выбранному городу, чтобы его можно было и для offers и для offersFavorites применять.